#!/bin/bash
##----------------
##Name: pkictl
##Description: A biased controller script to aid in common openssl management
##             tasks
##Date: 2015.01.08-01:39 
##Version: 0.6.0-alpha
##Requirements: openssl
##----------------

# Tunable settings
export PKICTL_ORG=${PKICTL_ORG:-"myorg.local"}     # Same as organizationName in openssl.cnf

# Script settings
export PKICTL_ROOT_DIR=${PKICTL_ROOT_DIR:-$PWD}

##############################################################################
## Setup
##############################################################################

init_folders() {
    if [[ -d "$caPath" ]]; then
        echo "Cannot init new CA with existing filename. Aborting."
        exit 1
    fi
    mkdir -p "${caPath}/private" "${caPath}/db" "${caPath}/crl" "${caPath}/certs"
    chmod 700 "${caPath}/private"
}

init_db() {
    cp /dev/null "${caPath}/db/${caName}.db"
    cp /dev/null "${caPath}/db/${caName}.db.attr"
    echo 01 > "${caPath}/db/${caName}.crt.srl"
    echo 01 > "${caPath}/db/${caName}.crl.srl"
}

##############################################################################
## Openssl commands
##############################################################################

gen_request() {
    openssl req -new \
        -config "$conf" \
        -out "${caPath}/${caName}.csr" \
        -keyout "${caPath}/private/${caName}.key"
    chmod 700 "${caPath}/private/${caName}.key"
}

sign_root_ca_request() {
    if [[ "$PKICTL_CA_EXTENSIONS" == "" ]] && [[ "$PKICTL_CA_POLICY" == "" ]]; then
        openssl ca -selfsign \
            -config "$conf" \
            -in "${caPath}/${caName}.csr" \
            -out "${caPath}/${caName}.crt"
    elif [[ "$PKICTL_CA_EXTENSIONS" != "" ]] && [[ "$PKICTL_CA_POLICY" == "" ]]; then
        openssl ca -selfsign \
            -config "$conf" \
            -in "${caPath}/${caName}.csr" \
            -out "${caPath}/${caName}.crt" \
            -extensions "$PKICTL_CA_EXTENSIONS"
    elif [[ "$PKICTL_CA_EXTENSIONS" == "" ]] && [[ "$PKICTL_CA_POLICY" != "" ]]; then
        openssl ca -selfsign \
            -config "$conf" \
            -in "${caPath}/${caName}.csr" \
            -out "${caPath}/${caName}.crt" \
            -policy "$PKICTL_CA_POLICY"
    else
        openssl ca -selfsign \
            -config "$conf" \
            -in "${caPath}/${caName}.csr" \
            -out "${caPath}/${caName}.crt" \
            -policy "$PKICTL_CA_POLICY" \
            -extensions "$PKICTL_CA_EXTENSIONS"
    fi

    if [[ "$?" -eq 0 ]]; then
        rm "${caPath}/${caName}.csr"
    fi
}

sign_request() {
    if [[ "$PKICTL_CA_EXTENSIONS" == "" ]] && [[ "$PKICTL_CA_POLICY" == "" ]]; then
        openssl ca \
            -config "$conf" \
            -in "${caPath}/${caName}.csr" \
            -out "${caPath}/${caName}.crt"
    elif [[ "$PKICTL_CA_EXTENSIONS" != "" ]] && [[ "$PKICTL_CA_POLICY" == "" ]]; then
        openssl ca \
            -config "$conf" \
            -in "${caPath}/${caName}.csr" \
            -out "${caPath}/${caName}.crt" \
            -extensions "$PKICTL_CA_EXTENSIONS"
    elif [[ "$PKICTL_CA_EXTENSIONS" == "" ]] && [[ "$PKICTL_CA_POLICY" != "" ]]; then
        openssl ca \
            -config "$conf" \
            -in "${caPath}/${caName}.csr" \
            -out "${caPath}/${caName}.crt" \
            -policy "$PKICTL_CA_POLICY"
    else
        openssl ca \
            -config "$conf" \
            -in "${caPath}/${caName}.csr" \
            -out "${caPath}/${caName}.crt" \
            -policy "$PKICTL_CA_POLICY" \
            -extensions "$PKICTL_CA_EXTENSIONS"
    fi

    if [[ "$?" -eq 0 ]]; then
        rm "${caPath}/${caName}.csr"
    fi
}

gen_crl() {
    openssl ca -gencrl \
        -config "$conf" \
        -out "${caPath}/crl/${caName}.crl"
}

gen_pem() {
    cat "${subCert}" "${parentCert}" > \
        "${caPath}/${PKICTL_ORG}-${caCertDepth}.chain.pem"
}

gen_pkcs12() {
    openssl pkcs12 -export \
        -name "${caName}" \
        -inkey "${caPath}/private/${caName}.key" \
        -in "${caPath}/${caName}.crt" \
        -certfile "${caPath}/${PKICTL_ORG}-${signingCaLabel}.chain.pem" \
        -out "${caPath}/${caName}.p12"
}

revoke_cert() {
    PKICTL_CRL_REASON=${PKICTL_CRL_REASON:-"unspecified"}
    openssl ca \
        -config "$conf" \
        -revoke "${caPath}/${caName}.crt" \
        -crl_reason "$PKICTL_CRL_REASON"
}

##############################################################################
## CLI Commands
##############################################################################

rootca() {
    declare caCertDepth="root"
    declare caName="${PKICTL_ORG}-${caCertDepth}.ca"
    declare caPath="${PKICTL_ROOT_DIR}/${caName}"
    declare conf="${PKICTL_ROOT_DIR}/${caName}.cnf"

    case "$1" in
        init)
            init_folders 
            init_db 
            ;;
        request)
            gen_request 
            ;;
        sign)
            declare PKICTL_CA_POLICY=${PKICTL_CA_POLICY:-""}
            declare PKICTL_CA_EXTENSIONS=${PKICTL_CA_EXTENSIONS:-"root_ca_ext"}
            sign_root_ca_request 
            ;;
        gencrl)
            gen_crl 
            ;;
        *)
            display_usage_rootca
            ;;
    esac
}

subca() {
    declare caCertDepth=${2:-"sub"}
    declare caParentLabel=${3:-"root"}
    declare caName="${PKICTL_ORG}-${caCertDepth}.root.ca"
    declare caPath="${PKICTL_ROOT_DIR}/${caName}"
    declare conf="${PKICTL_ROOT_DIR}/${caName}.cnf"

    case "$1" in
        init)
            init_folders 
            init_db 
            ;;
        request)
            gen_request 
            ;;
        sign)
            if [[ "$caParentLabel" == "root" ]]; then
                declare conf="${PKICTL_ROOT_DIR}/${PKICTL_ORG}-root.ca.cnf"
            else
                declare conf="${PKICTL_ROOT_DIR}/${PKICTL_ORG}-${caParentLabel}.root.ca.cnf"
            fi
            declare PKICTL_CA_POLICY=${PKICTL_CA_POLICY:-""}
            declare PKICTL_CA_EXTENSIONS=${PKICTL_CA_EXTENSIONS:-""}
            sign_request 
            ;;
        gencrl)
            gen_crl 
            ;;
        genpem)
            if [[ "$caParentLabel" == "root" ]]; then
                declare caName="${PKICTL_ORG}-root.ca"
                declare parentCert="${PKICTL_ROOT_DIR}/${caName}/${caName}.crt"
            else
                declare caName="${PKICTL_ORG}-${caParentLabel}"
                declare parentCert="${PKICTL_ROOT_DIR}/${caName}.root.ca/${caName}.chain.pem"
            fi
            declare subCert="${caPath}/${PKICTL_ORG}-${caCertDepth}.root.ca.crt"
            gen_pem
            ;;
        revoke)
            if [[ "$caParentLabel" == "root" ]]; then
                declare conf="${PKICTL_ROOT_DIR}/${PKICTL_ORG}-${caParentLabel}.ca.cnf"
            else
                declare conf="${PKICTL_ROOT_DIR}/${PKICTL_ORG}-${caParentLabel}.root.ca.cnf"
            fi
            revoke_cert
            if [[ "$caParentLabel" == "root" ]]; then
                declare caName="${PKICTL_ORG}-${caParentLabel}.ca"
            else
                declare caName="${PKICTL_ORG}-${caParentLabel}.root.ca"
            fi
            declare caPath="${PKICTL_ROOT_DIR}/${caName}"
            echo "Regenerating CRL..."
            gen_crl 
            ;;
        *)
            display_usage_subca
            ;;
    esac
}

usercert() {
    declare userCsrLabel=${2:-"sub.sub"}
    declare signingCaLabel=${3:-"sub"}
    declare caName="${PKICTL_ORG}-${userCsrLabel}.root.c"
    declare caPath="${PKICTL_ROOT_DIR}/${PKICTL_ORG}-${signingCaLabel}.root.ca"

    case "$1" in
        request)
            declare conf="${PKICTL_ROOT_DIR}/${PKICTL_ORG}-${userCsrLabel}.root.c.conf"
            gen_request 
            ;;
        sign)
            declare conf="${PKICTL_ROOT_DIR}/${PKICTL_ORG}-${signingCaLabel}.root.ca.cnf"
            declare PKICTL_CA_POLICY=${PKICTL_CA_POLICY:-""}
            declare PKICTL_CA_EXTENSIONS=${PKICTL_CA_EXTENSIONS:-""}
            sign_request 
            ;;
        genpkcs12)
            gen_pkcs12
            ;;
        revoke)
            declare conf="${PKICTL_ROOT_DIR}/${PKICTL_ORG}-${signingCaLabel}.root.ca.cnf"
            declare caName="${PKICTL_ORG}-${userCsrLabel}.root.c"
            revoke_cert
            declare caName="${PKICTL_ORG}-${caParentLabel}.root.ca"
            declare caPath="${PKICTL_ROOT_DIR}/${caName}"
            echo "Regenerating CRL..."
            gen_crl 
            ;;
        *)
            display_usage_usercert
            ;;
    esac
}

##############################################################################
## Usage Info
##############################################################################

display_usage_main() {
    echo "Usage: pkictl <subcommand> <action> <action args>"
    echo ""
    echo "Pkictl is a biased Public Key Infrastructure (PKI) management helper"
    echo "tool. It's designed to make certificate, key creation, and management"
    echo "tasks formal, easy to initiate, and easy to automate. The complexities"
    echo "of the openssl settings are to be absorbed by the various openssl.cnf"
    echo "files, saving only execution of the tasks for the script itself."
    echo ""
    echo -e "Subcommands:\tActions:"
    echo -e "\trootca"
    echo -e "\t\t(init|request|sign|gencrl|help)"
    echo ""
    echo -e "\tsubca"
    echo -e "\t\t(init|request|sign|gencrl|genpem|revoke|help) <subca label> [<signing CA label>]"
    echo ""
    echo -e "\tusercert"
    echo -e "\t\t(request|sign|genpkcs12|revoke|help) <request label> <signing CA label>"
    echo ""
    echo -e "\thelp"
    exit 1
}

display_usage_rootca() {
    echo "Usage: pkictl rootca <action>"
    echo ""
    echo "Create a root private key, CSR, and self sign to make a root CA"
    echo ""
    echo "actions:"
    echo -e "\tinit"
    echo -e "\t\tCreate folder structure."
    echo ""
    echo -e "\trequest"
    echo -e "\t\tCreate private key and certificate request."
    echo ""
    echo -e "\tsign"
    echo -e "\t\tSelf sign root CSR with root private key."
    echo ""
    echo -e "\tgencrl"
    echo -e "\t\tGenerate initial CRL file."
    exit 1
}

display_usage_subca() {
    echo "Usage: pkictl subca <action> <subca label> [<signing CA label>]"
    echo ""
    echo "Create a subordinate private key, CSR, and CA named <subca label>"
    echo "and sign it with senior CA named <signing CA label>."
    echo ""
    echo "Labeling Arguments:"
    echo "<subca label> must be supplied on every action usage. It is made up of"
    echo "the sub-levels from root and must coincide with the filename of its"
    echo "configuration file. So if \$PKICTL_ORG was \"sample.org\", the root CA"
    echo "is named \"sample.org-root.ca\". A subordinate CA below this one could"
    echo "have the name \"sub\". It would be named \"sample.org-sub.root.ca\". In"
    echo "these examples, the <subca label> is \"sub\" while the <signing CA label>"
    echo "would be \"root\". A third level below that could be \"tls.sub\", its"
    echo "name would be \"sample.org-tls.sub.root.ca\" and the <subca label> for"
    echo "it would be \"tls.sub\"."
    echo ""
    echo "actions:"
    echo -e "\tinit <subca label>"
    echo -e "\t\tCreate folder structure."
    echo ""
    echo -e "\trequest <subca label>"
    echo -e "\t\tCreate private key and certificate request."
    echo ""
    echo -e "\tsign <subca label> <signing CA label>"
    echo -e "\t\tSign <subca label> CSR with private key from"
    echo -e "\t\t<signing CA label> CA."
    echo ""
    echo -e "\tgencrl <subca label>"
    echo -e "\t\tGenerate initial CRL file."
    echo ""
    echo -e "\tgenpem <subca label> <signing CA label>"
    echo -e "\t\tConcatenate senior CA <signing CA label> certificate or"
    echo -e "\t\tcertificate chain with newly generated <subca label>"
    echo -e "\t\tcertificate."
    echo ""
    echo -e "\trevoke <subca label> <signing CA label>"
    echo -e "\t\tRevoke issued certificate <subca label> with CA"
    echo -e "\t\t<signing CA label> and automatically generate new CRL for"
    echo -e "\t\tCA <signing CA label>"
    exit 1
}

display_usage_usercert() {
    echo "Usage: pkictl usercert <action> <request label> <signing CA label>"
    echo ""
    echo "Create a user CSR, private key, certificate, and PKCS#12 bundle named"
    echo "<request label> and sign with subordinate CA named <signing CA label>."
    echo "Optionally, revoke issued user certificate <request label> with CA"
    echo "named <signing CA label>."
    echo ""
    echo "Labeling Arguments:"
    echo "<request label> must be supplied on every action usage. It is made up of"
    echo "the sub-levels from root and must coincide with the filename of its"
    echo "configuration file. So if \$PKICTL_ORG was \"sample.org\", the root CA"
    echo "is named \"sample.org-root.ca\". A subordinate signing CA two levels below"
    echo "could be \"tls.sub\", its name would be \"sample.org-tls.sub.root.ca\""
    echo "and its label \"tls.sub\". A user request could be named \"user.tls.sub\"."
    echo "Its full name would be \"sample.org-user.tls.sub.root.c\". Notice that for"
    echo "user certificate requests, we change the suffix to \"c\" from \"ca\". This"
    echo "is to label each as \"certificate\" or \"certificate authority\""
    echo "respectively. To sign this configuration, we use \"user.tls.sub\" as our"
    echo "<request label> and \"tls.sub\" as our <signing CA label>"
    echo ""
    echo "actions:"
    echo -e "\trequest <request label> <signing CA label>"
    echo -e "\t\tCreate private key and certificate request for <request label>."
    echo -e "\t\tCSR can be found in folder for <signing CA label>."
    echo ""
    echo -e "\tsign <request label> <signing CA label>"
    echo -e "\t\tSign <request label> CSR with private key from"
    echo -e "\t\t<signing CA label> CA."
    echo ""
    echo -e "\tgenpkcs12 <request label> <signing CA label>"
    echo -e "\t\tPackage user private key and signed certificate for <request label>"
    echo -e "\t\twith CA certificate chain from <signing CA label> in a PKCS#12"
    echo -e "\t\tbundle for export."
    echo ""
    echo -e "\trevoke <request label> <signing CA label>"
    echo -e "\t\tRevoke issued certificate <request label> with CA"
    echo -e "\t\t<signing CA label> and automatically generate new CRL for"
    echo -e "\t\tCA <signing CA label>"
    exit 1
}

##############################################################################
## Main
##############################################################################

main() {
    set -eo pipefail
    case "$1" in
        rootca)
            declare action="$2"
            rootca "$action"
            ;;
        subca)
            declare action="$2" subCaLabel="$3" subCaParentLabel=${4:-root}
            subca "$action" "$subCaLabel" "$subCaParentLabel"
            ;;
        usercert)
            declare action="$2" csrLabel="$3" caParentLabel=${4:-"sub"}
            usercert "$action" "$csrLabel" "$caParentLabel"
            ;;
        *)
            display_usage_main
            ;;
    esac
}

##############################################################################
## Runtime
##############################################################################
main "$@"
