#!/bin/bash
##----------------
##Name: pkictl_test
##Description: quick and simple testing to make sure new changes
##             don't blow things up
##Requirements: openssl pkictl
##----------------

export PKICTL_CMD=${PKICTL_CMD:-../pkictl}
export PKICTL_ORG=${PKICTL_ORG:-"myorg.local"}
export PKICTL_CONFIG_DIR="$PWD/configs"
export PKICTL_SSL_DIR="$PWD/client_ssl_dir"
export PKICTL_CA_POLICY="policy_anything"
export PKICTL_SAFE_TEST="true"

setup() {
    mkdir -p "$PKICTL_TEST_DIR"
    mkdir -p "$PKICTL_SSL_DIR"
}

cleanup() {
    rm -rf "$PKICTL_TEST_DIR"
    rm -rf "$PKICTL_SSL_DIR"
}

test_rootca() {
    echo "#######################################"
    echo "running rootca tests"
    echo ""
    "$PKICTL_CMD" rootca init
    "$PKICTL_CMD" rootca request
    "$PKICTL_CMD" rootca sign
    "$PKICTL_CMD" rootca gencrl
}

test_subca() {
    echo "#######################################"
    echo "running subca tests"
    echo ""
    echo "setting up sub CA..."
    echo ""
    "$PKICTL_CMD" subca init sub
    "$PKICTL_CMD" subca request sub
    "$PKICTL_CMD" subca sign sub root
    "$PKICTL_CMD" subca gencrl sub
    "$PKICTL_CMD" subca genpem sub root

    echo ""
    echo "setting up tls.sub signing CA..."
    echo ""
    "$PKICTL_CMD" subca init tls.sub
    "$PKICTL_CMD" subca request tls.sub
    "$PKICTL_CMD" subca sign tls.sub sub
    "$PKICTL_CMD" subca gencrl tls.sub
    "$PKICTL_CMD" subca genpem tls.sub sub

    echo ""
    echo "setting up email.sub signing CA..."
    echo ""
    "$PKICTL_CMD" subca init email.sub
    "$PKICTL_CMD" subca request email.sub
    "$PKICTL_CMD" subca sign email.sub sub
    "$PKICTL_CMD" subca gencrl email.sub
    "$PKICTL_CMD" subca genpem email.sub sub
    "$PKICTL_CMD" subca revoke email.sub sub
}

test_eecert() {
    echo "#######################################"
    echo "running eecert tests"
    echo ""
    echo "setting up node.tls.sub user certificate..."
    echo ""
    "$PKICTL_CMD" eecert request node.tls.sub tls.sub testnodename
    "$PKICTL_CMD" eecert sign testnodename tls.sub
    "$PKICTL_CMD" eecert genpkcs12 testnodename tls.sub nodeexportname

    echo ""
    echo "setting up user.mail.sub user certificate..."
    echo ""
    "$PKICTL_CMD" eecert request user.email.sub email.sub testusername
    "$PKICTL_CMD" eecert sign testusername email.sub
    "$PKICTL_CMD" eecert genpkcs12 testusername email.sub userexportname
    "$PKICTL_CMD" eecert revoke testusername email.sub

    echo ""
    echo "testing default naming..."
    echo ""
    "$PKICTL_CMD" eecert request user.email.sub email.sub
    "$PKICTL_CMD" eecert sign user.email.sub email.sub
    "$PKICTL_CMD" eecert genpkcs12 user.email.sub email.sub userexportname2
    "$PKICTL_CMD" eecert revoke user.email.sub email.sub

    echo ""
    echo "testing duplicates..."
    echo "make sure to make different common names then before"
    echo ""
    "$PKICTL_CMD" eecert request user.email.sub email.sub testusername_new
    "$PKICTL_CMD" eecert sign testusername_new email.sub
    "$PKICTL_CMD" eecert genpkcs12 testusername_new email.sub userexportname3
    "$PKICTL_CMD" eecert revoke testusername_new email.sub
}

test_eecert_import(){
    echo "#######################################"
    echo "running eecert import tests"
    echo ""
    echo "importing userexportname client key/certs and chain..."
    echo ""
    PKICTL_PKCS12_PASS="asdfasdf" "$PKICTL_CMD" eecert import userexportname
    PKICTL_PKCS12_PASS="asdfasdf" "$PKICTL_CMD" eecert import userexportname2
    PKICTL_PKCS12_PASS="asdfasdf" "$PKICTL_CMD" eecert import userexportname3
}

test_openssl_bin(){
    echo "#######################################"
    echo "running openssl bin tests"
    echo ""

    if [ -z ${OPENSSL_BIN+x} ]; then
        echo "you must specify a different env var OPENSSL_BIN in order to test this"
        return 1
    fi

    echo "using openssl version $($OPENSSL_BIN version)"
    echo ""
    main rootca
    main subca
    main eecert
    main eecert-import
}

main() {
    set -eo pipefail
    case "$1" in
        openssl-bin)
            test_openssl_bin
            ;;
        rootca)
            declare PKICTL_TEST_DIR="$PWD/rootca"
            export PKICTL_CA_DIR="$PKICTL_TEST_DIR"
            cleanup
            setup
            test_rootca
            ;;
        subca)
            declare PKICTL_TEST_DIR="$PWD/subca"
            export PKICTL_CA_DIR="$PKICTL_TEST_DIR"
            cleanup
            cp -r "$PWD/rootca" "$PWD/subca"
            setup
            test_subca
            ;;
        eecert)
            declare PKICTL_TEST_DIR="$PWD/eecert"
            export PKICTL_CA_DIR="$PKICTL_TEST_DIR"
            export PKICTL_IMPORT_DIR="${PKICTL_TEST_DIR}/${PKICTL_ORG}-email.sub.root.ca/export"
            cp -r "$PWD/subca" "$PWD/eecert"
            setup
            test_eecert
        eecert-import)
            declare PKICTL_TEST_DIR="$PWD/eecert"
            export PKICTL_CA_DIR="$PKICTL_TEST_DIR"
            export PKICTL_IMPORT_DIR="${PKICTL_TEST_DIR}/${PKICTL_ORG}-email.sub.root.ca/export"
            test_eecert_import
            ;;
        *)
            echo "Specify a sub-command to test..."
            echo "They are run in order and one at a time:"
            echo "rootca, subca, eecert, eecert-import"
            ;;
    esac
}

main "$@"
