#!/bin/bash
##----------------
##Name: pkictl_test
##Description: quick and simple testing to make sure new changes
##             don't blow things up
##Requirements: openssl pkictl
##----------------

export PKICTL_CMD=${PKICTL_CMD:-../pkictl}
export PKICTL_ORG=${PKICTL_ORG:-"myorg.local"}

setup() {
    mkdir -p "$PKICTL_TEST_DIR"
    cp configs/* "$PKICTL_TEST_DIR"
}

cleanup() {
    rm -rf "$PKICTL_TEST_DIR"
}

test_rootca() {
    echo "#######################################"
    echo "running rootca tests"
    echo ""
    "$PKICTL_CMD" rootca init
    "$PKICTL_CMD" rootca request
    "$PKICTL_CMD" rootca sign
    "$PKICTL_CMD" rootca gencrl
}

test_subca() {
    test_rootca

    echo "#######################################"
    echo "running subca tests"
    echo ""
    echo "setting up sub CA..."
    echo ""
    "$PKICTL_CMD" subca init sub
    "$PKICTL_CMD" subca request sub
    "$PKICTL_CMD" subca sign sub root
    "$PKICTL_CMD" subca gencrl sub
    "$PKICTL_CMD" subca genpem sub root

    echo ""
    echo "setting up tls.sub signing CA..."
    echo ""
    "$PKICTL_CMD" subca init tls.sub
    "$PKICTL_CMD" subca request tls.sub
    "$PKICTL_CMD" subca sign tls.sub sub
    "$PKICTL_CMD" subca gencrl tls.sub
    "$PKICTL_CMD" subca genpem tls.sub sub

    echo ""
    echo "setting up email.sub signing CA..."
    echo ""
    "$PKICTL_CMD" subca init email.sub
    "$PKICTL_CMD" subca request email.sub
    "$PKICTL_CMD" subca sign email.sub sub
    "$PKICTL_CMD" subca gencrl email.sub
    "$PKICTL_CMD" subca genpem email.sub sub
    "$PKICTL_CMD" subca revoke email.sub sub
}

test_eecert() {
    test_subca

    echo "#######################################"
    echo "running eecert tests"
    echo ""
    echo "setting up node.tls.sub user certificate..."
    echo ""
    "$PKICTL_CMD" eecert request node.tls.sub tls.sub testnodename
    "$PKICTL_CMD" eecert sign testnodename tls.sub
    "$PKICTL_CMD" eecert genpkcs12 testnodename tls.sub nodeexportname

    echo ""
    echo "setting up user.mail.sub user certificate..."
    echo ""
    "$PKICTL_CMD" eecert request user.email.sub email.sub testusername
    "$PKICTL_CMD" eecert sign testusername email.sub
    "$PKICTL_CMD" eecert genpkcs12 testusername email.sub userexportname
    "$PKICTL_CMD" eecert revoke testusername email.sub
}

main() {
    set -eo pipefail
    case "$1" in
        rootca)
            PKICTL_TEST_DIR="$PWD/rootca"
            export PKICTL_ROOT_DIR=$PKICTL_TEST_DIR
            cleanup
            setup
            test_rootca
            ;;
        subca)
            PKICTL_TEST_DIR="$PWD/subca"
            export PKICTL_ROOT_DIR=$PKICTL_TEST_DIR
            cleanup
            setup
            test_subca
            ;;
        eecert)
            PKICTL_TEST_DIR="$PWD/eecert"
            export PKICTL_ROOT_DIR=$PKICTL_TEST_DIR
            cleanup
            setup
            test_eecert
            ;;
        *)
            ;;
    esac
}

main "$@"
